apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base

namespace: abuse-api-dev
images:
- name: gdartifactory1.jfrog.io/docker-dcu-local/requeue
  newTag: dev

patches:
- patch: |-
    - op: add
      path: "/spec/schedule"
      value: "*/5 * * * *"
  target:
    kind: CronJob
    name: requeue

configMapGenerator:
- literals:
  - sysenv=dev
  - ELASTIC_APM_ENVIRONMENT=dev
  name: env-specific-values
