apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: requeue
  namespace: abuse-api-prod
  labels:
    app: requeue
spec:
  schedule: " 0 1 * * *"

  # Deadline in seconds for starting the job if it misses its scheduled time.
  startingDeadlineSeconds: 60

  concurrencyPolicy: Forbid

  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3

  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: requeue
        spec:
          restartPolicy: OnFailure
          imagePullSecrets:
            - name: dcu-artifactory-creds
          containers:
            - name: requeue
              imagePullPolicy: Always
              image: docker-dcu-local.artifactory.secureserver.net/requeue:REPLACE_WITH_GIT_COMMIT
              env:
                - name: sysenv
                  value: "prod"
                - name: BUILD_DATE
                  value: "THIS_STRING_IS_REPLACED_DURING_BUILD"
                - name: MULTIPLE_BROKERS
                  valueFrom:
                    secretKeyRef:
                      name: amqp-shared-creds
                      key: multiple_brokers_pdna