apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base

namespace: abuse-api-prod
images:
- name: docker-dcu-local.artifactory.secureserver.net/requeue
  newTag: REPLACE_WITH_GIT_COMMIT

configMapGenerator:
- literals:
  - sysenv=prod
  name: env-specific-values