apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base

namespace: abuse-api-ote
images:
- name: docker-dcu-local.artifactory.secureserver.net/requeue
  newTag: ote

configMapGenerator:
- literals:
  - sysenv=ote
  - ELASTIC_APM_ENVIRONMENT=ote
  name: env-specific-values