apiVersion: batch/v1
kind: CronJob
metadata:
  name: requeue
  namespace: abuse-api-dev
  labels:
    app: requeue
spec:
  schedule: " 0 1 * * *"

  # Deadline in seconds for starting the job if it misses its scheduled time.
  startingDeadlineSeconds: 60

  concurrencyPolicy: Forbid

  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3

  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: requeue
        spec:
          restartPolicy: OnFailure
          imagePullSecrets:
            - name: artifactory-saas-creds
          containers:
            - name: requeue
              imagePullPolicy: Always
              image: gdartifactory1.jfrog.io/docker-dcu-local/requeue
              envFrom:
              - configMapRef:
                  name: env-specific-values
              env:
                - name: BUILD_DATE
                  value: "THIS_STRING_IS_REPLACED_DURING_BUILD"
                - name: MULTIPLE_BROKERS
                  valueFrom:
                    secretKeyRef:
                      name: amqp-shared-creds
                      key: multiple_brokers_pdna
                - name: ELASTIC_APM_SERVER_URL
                  valueFrom:
                    secretKeyRef:
                      name: apm-access
                      key: url
                - name: ELASTIC_APM_SECRET_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: apm-access
                      key: secret
